# nixpacks.toml

[phases.setup]
# Extra system dependencies to install
nixPkgs = [
  "chromium",
  "chromiumDriver"
]

[phases.install]
# Make sure Python deps are installed
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
