# nixpacks.toml

[phases.setup]
# Extra system dependencies to install
nixPkgs = [
  "chromium",
  "chromedriver",
  "ffmpeg",
  "unzip",
  "wget"
]

[phases.install]
# Call pip from the venv path Nixpacks sets up
cmds = ["/opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
